### ISSUE TITLE
[FEATURE]: Allow downstream templating of the annotations based on the annotated resource

### ISSUE THREAD

**Issue by shanduur** [anza-labs/scribe#13]
### Is your feature request related to a problem? Please describe.

Currently, the annotations propagated by Scribe are static and do not adapt to the context of the resources they are applied to. This can be limiting when dealing with dynamic annotations that need to reflect the specific attributes of each resource (e.g., resource name, namespace).

### Describe the solution you'd like.

I would like the ability to use templating within annotations so that the values can be dynamically populated based on the annotated resource's metadata or spec fields. For example, annotations could make use of Go templating syntax to reference metadata fields, such as the resource's name.

**Example:**

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: example
  annotations:
    # annotations below will be propagated to all resources
    # observed by the scribe controller - e.g. Deployments
    scribe.anza-labs.dev/annotations: |
      app.kubernetes.io/name={{ .metadata.name }}
```

**Result:**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  annotations:
    app.kubernetes.io/name: example-deployment
```

### Describe alternatives you've considered.

N/A
