### ISSUE TITLE
[FEATURE]: Delete annotations from objects after they are deleted from the namespace

### ISSUE THREAD

**Issue by shanduur** [anza-labs/scribe#14]
### Is your feature request related to a problem? Please describe.

Currently, when annotations are removed from the namespace, they remain on the previously annotated objects (e.g., Deployments, Services) unless manually removed. This can lead to outdated or incorrect annotations persisting on resources, which might cause confusion or unwanted behavior.

### Describe the solution you'd like.

I would like Scribe to automatically remove annotations from resources when they are deleted from the namespace's annotations. This would ensure that resources stay in sync with the current state of the namespace's annotations.

**Example:**

1. Namespace `example` has the following annotation:
    ```yaml
    apiVersion: v1
    kind: Namespace
    metadata:
      name: example
      annotations:
        scribe.anza-labs.dev/annotations: |
          app.kubernetes.io/name=example
    ```
2. The annotation is propagated to all resources within the namespace.
3. Later, the annotation is removed from the namespace:
    ```yaml
    apiVersion: v1
    kind: Namespace
    metadata:
      name: example
      annotations:
        scribe.anza-labs.dev/annotations: ""
    ```
4. Scribe should detect the change and remove the `app.kubernetes.io/name=example` annotation from all relevant resources automatically.

### Describe alternatives you've considered.

1. Manually removing annotations from resources when they are no longer needed, which can be time-consuming and error-prone in large environments.
2. Using custom scripts or jobs to periodically clean up outdated annotations, but this adds complexity and overhead.
